export const GET_PRODUCT_BYID = "GET_PRODUCT_BYID";
export const GET_PRODUCT_BY_CATEGORY ="GET_PRODUCT_BY_CATEGORY";
export const GET_PRODUCT_SEARCH = "GET_PRODUCT_SEARCH";
export const GET_PRODUCT_BYADMIN = "GET_PRODUCT_BYADMIN";
export const ADD_PRODUCT="ADD_PRODUCT";